# 前端项目容器内的 Nginx 配置，核心作用是托管静态文件、解决单页应用刷新 404 问题，不需要配置反向代理和 gzip（主 Nginx 已经处理）
server {
        listen 4200;
        server_name localhost;

        # 前端打包后的静态文件根目录（必须和 Dockerfile 中 dist 目录一致）
        root /usr/share/nginx/html;
        index index.html;

        set $csp "
                default-src 'self';
                script-src 'self' 'wasm-unsafe-eval' 'nonce-$fixed_nonce';
                style-src 'self' 'nonce-$fixed_nonce' 'unsafe-hashes';
                img-src 'self' data: blob: https:;
                connect-src 'self'
                https://*.arcgis.com
                https://*.arcgisonline.com
                https://utility.arcgis.com
                https://basemaps-api.arcgis.com;
                font-src 'self';
                frame-src 'self' https://*.arcgis.com;
                object-src 'none';
                worker-src 'self' blob:;
                base-uri 'self';
                form-action 'self';
                frame-ancestors 'self';
        ";
        add_header Content-Security-Policy $csp;
        sub_filter_types text/html
        sub_filter_once off;
        sub_filter '{{NONCE}}' $fixed_nonce;
        sub_filter '{{CSP}}' $csp;
        sub_filter '<script>' '<script nonce="$fixed_nonce">';
        sub_filter '<style>' '<style nonce="$fixed_nonce">';
        # 核心：解决 Vue/React 单页应用刷新 404
        location / {
                sub_filter_types text/html;
                sub_filter_once off;
                sub_filter '{{NONCE}}' $fixed_nonce;
                sub_filter '{{CSP}}' $csp;

                try_files $uri $uri/ /index.html;
        }

        location /api {
                proxy_pass http://backend_container:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Prefix /api;

                proxy_redirect http://backend_container:3000/ /api/;

                proxy_connect_timeout 30s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
        }

        # 优化：静态资源缓存策略，减轻服务器压力
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                # 缓存 7 天
                expires 7d;
                # 开启缓存控制
                add_header Cache-Control "public, max-age=604800";
                # 禁止修改缓存文件
                add_header Pragma "public";
        }

        # VitePress 的路由元数据 json，短缓存 1 小时
        location ~* \.json$ {
                expires 1h;
                add_header Cache-Control "public, max-age=3600";
        }

        # HTML 文件不缓存，确保发布后用户立即看到新内容
        location ~* \.html$ {
                expires -1;
                add_header Cache-Control "no-cache, no-store, must-revalidate";
        }

        # 禁止访问隐藏文件（如 .env .gitignore）
        location ~ /\.(?!well-known).* {
                deny all;
        }
}