worker_processes 1;
error_log logs/error.log warn;
pid logs/nginx.pid;
events {
    worker_connections 1024;
}
http {
    include mime.types;
    default_type application/octet-stream;
    
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    
    access_log logs/access.log main;
    
    map $pid$hostname $fixed_nonce_raw {
        default $pid$hostname;
    }
    map $fixed_nonce_raw $fixed_nonce {
        default "202603211451202603211451";
        "~^([0-9a-zA-Z]+)"  "$1";
    }
    
    server {
        listen 80;
        
        location = /frontend {
                return 301 /frontend/;
        }
        location = /backend {
                return 301 /backend/;
        }

        # 2. 前端应用 1：/frontend/ 路径转发
        location /frontend/ {
                # 转发到 app1 容器的 80 端口
                proxy_pass http://frontend_container:4200/;

                # 传递请求头 - 后端获取真实客户端信息
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Prefix /frontend;

                # 修正后端跳转地址，避免返回容器内部地址
                proxy_redirect http://app1_nginx/ /frontend/;

                # 超时配置 - 防止连接挂死
                proxy_connect_timeout 30s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
        }

        # 3. 前端应用 2：/backend/ 路径转发
        location /backend/ {
                proxy_pass http://backend_container:3000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Prefix /backend;

                proxy_redirect http://app2_nginx/ /backend/;

                proxy_connect_timeout 30s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
        }
    }
}